### ISSUE TITLE
Virtual host configuration is ignored

### ISSUE THREAD

**Issue by wizonesolutions** [geerlingguy/ansible-role-apache#108]
It seems like defaults are being used for the virtual hosts rather than my configuration. I know I am going to figure this out as soon as I post the issue, but I have gone through the debugging steps I could think of (spelling, syntax, spelling again, syntax again, role name spelling, no really, copy-pasting variable names from the documentation, etc.)

Here is the relevant part:

````yaml
    - role: geerlingguy.apache
      apache_ignore_missing_ssl_certificate: true
      apache_remove_default_vhost: true
      apache_vhosts:
        - servername: '{{ fps_server_name }}'
          serveralias: '{{ fps_server_alias }}'
          documentroot: '{{ fps_docroot }}'
          extra_parameters: |
                ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ fps_docroot }}"
      apache_vhosts_ssl:
        - servername: '{{ fps_server_name }}'
          serveralias: '{{ fps_server_alias }}'
          documentroot: '{{ fps_docroot }}'
          extra_parameters: |
                ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ fps_docroot }}"
          certificate_file: '{{ fps_cert_location }}'
          certificate_key_file: '{{ fps_privkey_location }}'
          certificate_chain_file: '{{ fps_chain_location }}'
````

Save me, @geerlingguy-sensei!
