### ISSUE TITLE
extra_parameters for apache_vhosts_ssl

### ISSUE THREAD

**Issue by frost-byte** [geerlingguy/ansible-role-apache#125]
I'm able to use the | (literal style) for line continuation for apache_vhosts, but ansible complains when I try to use the same convention for a vhost using ssl.

Following the example in the docs where you show a mapping for apache_vhosts_ssl, if I add extra_parameters: | it complains about the |

Is there a different convention I'm supposed to use here?
What's the proper way to use a multi-line string value for a key in a mapping?

**Comment by frost-byte** [comment]
Well, I worked around the issue by assigning the values for extra_parameters to another variable and then assigning that variable to extra_parameters in the apache_vhosts_ssl mapping. (I needed to reuse them anyway)

```
apache_vhosts_extra_param: |
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond $1 !^(index\.php|assets|res|robots\.txt)
  RewriteRule ^(.*)$ index.php/$1 [L]

apache_vhosts_ssl:
  - {
    servername: "{{host_name}}",
    documentroot: "{{www_document_root}}",
    certificate_file: "{{www_ssl_cert_path}}/cert.pem",
    certificate_key_file: "{{www_ssl_cert_path}}/privkey.pem",
    certificate_chain_file: "{{www_ssl_cert_path}}/chain.pem",
    serveralias: "{{www_subdomain}}",
    serveradmin: "admin@{{www_site_name}}",
    options: "+Indexes +FollowSymLinks +MultiViews",
    allow_override: "All",
    extra_parameters: "{{apache_vhosts_extra_param}}"
  }
```

**Comment by shanedroid** [comment]
I also observed this using `2.0.1` of the role with Ansible `2.2.1.0`, and used the following instead which worked for me:
```
apache_vhosts_ssl:
  - servername: "{{ host_name }}"
    serveradmin: "{{ admin_email }}"
    documentroot: "{{ app__dir }}/public"
    certificate_file: "{{ ssl__cert_path }}/cert"
    certificate_key_file: "{{ ssl__cert_path }}/key"
    certificate_chain_file: "{{ ssl__cert_path }}/chain"
    options: "+Indexes +FollowSymLinks"
```
I am not exactly sure why the chomping indicator `|` works as expected for the `extra_parameters` when it is standalone but not when it is a key within a hash, I chalked this up as a YAML oddity and carried on.
