### ISSUE TITLE
yaml examples

### ISSUE THREAD

**Issue by TinajaLabs** [geerlingguy/ansible-role-apache#129]
Not sure I understand how to set variables in my playbook that calls this role.

I am trying to get graphite/grafana installed using this role for the apache part.

Here's what I see in the defaults/main.yml
```
apache_vhosts:
  # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: "local.dev"
    documentroot: "/var/www/html
```

I want to set servername to "graphite" and documentroot to "/opt/graphite/webapp"

Here's what I have for the role in my playbook file:
```
    roles:
        - { role: geerlingguy.apache,
            apache_listen_ip: "*",
            apache_listen_port: 8080,
            apache_create_vhosts: true,
            apache_vhosts_filename: "graphite.conf",
            apache_vhosts: { servername = "graphite", documentroot = "/opt/graphite/webapp" }
          }
```

My confusion is that I don't see any examples in the readme that indicate how one is to translate what is  in defaults/main.yml and how one is to format that into a role call in the playbook.

I suppose I could change the values in the defaults, but then I'd have a modified version of the role module which would not be a best practice.

With the above in my playbook, I get this error:
```
TASK [geerlingguy.apache : Add apache vhosts configuration.] *******************
fatal: [mf-tinaja-gr]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'ansible.parsing.yaml.objects.AnsibleUnicode object' has no attribute 'servername'"}```
 
If I remove that variable, servername = "graphite", from my playbook, the error still occurs.

Thanks for any advice.

**Comment by geerlingguy** [comment]
@TinajaLabs - It's usually better/easier to define the variables separately (in `vars:` in your playbook, or in an included `vars_files:` file). But if you need to define the variables inline like that, you need to define each vhost as an element of an array:

```yaml
    roles:
        - role: geerlingguy.apache
          apache_listen_ip: "*"
          apache_listen_port: 8080
          apache_create_vhosts: true
          apache_vhosts_filename: "graphite.conf"
          apache_vhosts:
            - servername: "graphite"
              documentroot: "/opt/graphite/webapp"
```

Trying to get things working using the JSON-like literal object syntax (with nested `{ }` and commas) is often really difficult to do (while preserving nested arrays, etc.), and prone to errors like the one you're seeing. It's more readable and easier to format using YAML fully for the object/array definitions.

The above chunk of YAML should work for what you're trying to do.
