### ISSUE TITLE
Role is running twice when include-vars is used

### ISSUE THREAD

**Issue by thsur** [geerlingguy/ansible-role-apache#162]
I have two vars files, one with default settings for a vanilla LAMP stack, the other for site-specific settings. The latter gets included when a certain var is true, and sets ```apache_listen_port``` to 81.

So the playbook looks like this:
```
tasks:
  
    # Site-specific vars

    - include_vars: ./vars/drupal.yml
      when: drupal_site

    # Default roles

   ...

    - include_role:
        name: geerlingguy.apache
    - include_role:
        name: geerlingguy.apache-php-fpm
```

When ```drupal_site``` is true, ```geerlinguy.apache``` is running twice, once before, once after ```geerlingguy.apache-php-fpm```, the second time ignoring the included vars, thus setting ```apache_listen_port``` back to 80:

```
TASK [include_role : geerlingguy.apache] **********************************************************************************************************
...
TASK [geerlingguy.apache : Configure Apache.] **********************************************************************************************************
changed: [...] => (item={'regexp': '^Listen ', 'line': 'Listen 81'}) => {"backup": "", "changed": true, "item": {"line": "Listen 81", "regexp": "^Listen "}, "msg": "line replaced"}
...
TASK [include_role : geerlingguy.apache-php-fpm] **********************************************************************************************************
...
TASK [geerlingguy.apache : Configure Apache.] **********************************************************************************************************
changed: [...] => (item={'regexp': '^Listen ', 'line': 'Listen 80'}) => {"backup": "", "changed": true, "item": {"line": "Listen 80", "regexp": "^Listen "}, "msg": "line replaced"}
```

When the vars file is not included, everything runs fine. Also, when setting the listen port as a fact inside my play, the role still runs twice, but respects my settings on both runs, so this is not a real issue for me. But since it's a bit odd, I thought I'd share.
