### ISSUE TITLE
Fails when running --check

### ISSUE THREAD

**Issue by JorisVanEijden** [geerlingguy/ansible-role-apache#20]
Error: One or more undefined variables: 'dict' object has no attribute 'stdout'

```yaml
# Figure out what version of Apache is installed.
- name: Get installed version of Apache.
  command: "{{ apache_daemon }} -v"
  changed_when: false
  register: _apache_version
- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"
```

Probably because the command module is skipped in check mode which fills the _apache_version variable with {'skipped': True}. 

Would this approach make sense?
```yaml
- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"
    when: not _apache_version|skipped
```
