### ISSUE TITLE
Issue with Ansible 3.6.9 

### ISSUE THREAD

**Issue by i1337m** [geerlingguy/ansible-role-apache#221]
Hi, I've a issue when I try to run the playbook on a ubuntu server 20.04, 
Playbook :
```
---
- name: Install apache
  hosts: webapp
  become: yes
  become_user: root
  remote_user: root
  roles:
  - { role: geerlingguy.apache }    
  ```
The full traceback is:
```

  File "/tmp/ansible_ansible.legacy.command_payload_lj6fl4u6/ansible_ansible.legacy.command_payload.zip/ansible/module_utils/basic.py", line 2726, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
fatal: [server-webapp]: FAILED! => {
    "changed": false,
    "cmd": "/usr/sbin/apache2 -v",
    "invocation": {
        "module_args": {
            "_raw_params": "/usr/sbin/apache2 -v",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "[Errno 2] No such file or directory: b'/usr/sbin/apache2'",
    "rc": 2
}
```
Any idea how to fix this ? 
thanks
