### ISSUE TITLE
SSL vhost is throwing error when starting Apache

### ISSUE THREAD

**Issue by ronalddemneri** [geerlingguy/ansible-role-apache#231]
Got the role using ansible-galaxy and I added the ssl vhost with a very basic setup, just for testing:

```
        apache_vhosts_ssl:
          - servername: "www.eaxmple.com"
            documentroot: "/var/www/html"
            extra_parameters: |
                ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/html"
            certificate_file: "/etc/ssl/certs/ssl-cert-snakeoil.pem"
            certificate_key_file: "/etc/ssl/private/ssl-cert-snakeoil.key" 
```

but when trying to start apache, I received the error about directive `SSLEngine on` (don't remember exactly the error message I got).
When checking the configuration, I noticed that the SSL vhost in the target server was missing the `<ifModule mod_ssl.so>...</ifModule>` directives. Once I added that to the configuration file, apache was able to start.

As a matter of fact, the default-ssl.conf file was in place, even though I had the `apache_remove_default_vhost` set to true.
