### ISSUE TITLE
/bin/systemctl Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by basictheprogram** [geerlingguy/ansible-role-apache#232]
Attempting to use this role with Ubunu Bionic 18.04 and ran `molecule converge` to understand how it works. The converge throws an error
```
TASK [geerlingguy.apache : Ensure Apache has selected state and enabled on boot.] ***
fatal: [instance]: FAILED! => {"changed": false, "cmd": "/bin/systemctl", "msg": "Failed to connect to bus: No such file or directory", "rc": 1, "stderr": "Failed to connect to bus: No such file or directory\n", "stderr_lines": ["Failed to connect to bus: No such file or directory"], "stdout": "", "stdout_lines": []}
```
```
Docker Desktop 4.3.1 (72247)
```
```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G9323
```
```
$ ansible --version
ansible 2.9.16.post0
  config file = None
  configured module search path = ['/Users/tanner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/py3-ansible/src/ansible/lib/ansible
  executable location = /Users/tanner/projects/py3-ansible/src/ansible/bin/ansible
  python version = 3.9.7 (default, Oct 13 2021, 06:43:37) [Clang 11.0.0 (clang-1100.0.33.17)]
```
```
 $ MOLECULE_DISTRO=ubuntu1804 molecule converge
```
```
molecule login to the image reports
# lsb_release --all
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```
I thought the molecule.yml `volumes` and `privileged` took care of thole dbus, systemd problem?
```
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
```
