### ISSUE TITLE
Won't work with Apache 2.4 on RedHat 6.5

### ISSUE THREAD

**Issue by joekhoobyar** [geerlingguy/ansible-role-apache#41]
I set the following in `group_vars/all.yml`

``` yaml
apache_packages:
  - httpd24-httpd
  - httpd24-httpd-devel
  - openssh

apache_enablerepo: rhui-REGION-rhel-server-rhscl
```

It installs version 2.4, but then can't find the daemon because of the fact that the RPM installs itself to `/opt/rh/httpd24/root`.  It is close, but not completely solved.  We would need a vars/RedHat65.yml to solve it - since I can't override settings like `apache_daemon_path` from the group_vars.

Any suggestions?

**Comment by geerlingguy** [comment]
@joekhoobyar - So if I make `apache_daemon_path` a configurable variable, should that solve the issue, do you think?

**Comment by liquidat** [comment]
Actually, adding a RHEL65.yml would not help here. The reason the rpm installs to` /opt/` is that the RPM comes from an additional software repository (the software collections) which install to '/opt/'.
Thus the only option I see is to be able to make the 'apache_daemon_path' a variable - though I am not sure if that's all what is needed...

**Comment by kimamula** [comment]
The following worked for me.

```yml
apache_service: httpd24-httpd
apache_daemon_path: /opt/rh/httpd24/root/usr/sbin/
apache_server_root: /opt/rh/httpd24/root/etc/httpd
apache_conf_path: "{{ apache_server_root }}/conf.d"
```
