### ISSUE TITLE
Ability to pass ProxyPass

### ISSUE THREAD

**Issue by gitoutthere** [geerlingguy/ansible-role-apache#42]
Would it be possible to add vars so I could pass ProxyPass info for a host? Sorry if this is not a issue or filed in a wrong place

**Comment by geerlingguy** [comment]
You should be able to add this inside the `extra_parameters` for a given `apache_vhosts` entry. I think I'll add an example to the README, because you're not the first who's asked about this!

**Comment by geerlingguy** [comment]
Please see the updated example in the README, about the use of `extra_parameters` in an `apache_vhosts` block.

**Comment by geerlingguy** [comment]
Also, I recently had to use ProxyPass in a project, here's the config I was using:

```yaml
apache_vhosts:
  - servername: "local.example.com"
    serveralias: "local.exampletwo.com"
    documentroot: "/example"
    extra_parameters: |
      RewriteEngine On
      RewriteCond %{REQUEST_URI} !^/[sites|misc|modules].*$ [NC]
      RewriteCond %{REQUEST_URI} !^/exampletwo.*$ [NC]
      RewriteRule ^(.*)$ http://localhost/exampletwo$1 [P]
      ProxyPassReverse / http://localhost/exampletwo/
```
