### ISSUE TITLE
Role execution fails at Add apache vhosts configuration task

### ISSUE THREAD

**Issue by swarup-donepudi** [geerlingguy/ansible-role-apache#51]
Hi,

I have cloned the repo and did ran the playbook with out making any changes to the role and the play fails with the below error.

TASK: [geerlingguy-apache | Add apache vhosts configuration.] *****************
fatal: [default] => One or more undefined variables: 'str object' has no attribute 'servername'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/donepusw/pg-play.retry

default                    : ok=17   changed=11   unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
With the way this role is set up, you have to provide at least a `servername` and `documentroot` for each configured `apache_vhost`, as in the documentation:

```yaml
apache_vhosts:
  # Additional optional properties: 'serveradmin, serveralias, extra_parameters'.
  - servername: "local.dev"
    documentroot: "/var/www/html"
```
