### ISSUE TITLE
Add documentation for apache_vhosts_ssl ProxyPassMatch extra_parameters

### ISSUE THREAD

**Issue by dmurphy1** [geerlingguy/ansible-role-apache#73]
After updating my Drupal VM from release `2.1.2` to `2.2.1` and following the release notes for new variables in `config.yml`, specifically for the `ProxyPassMatch parameter` below: 
```
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"
```
I found that my sites served over SSL stopped working. To fix this issue, I added `extra_parameters: 'ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"',` to my
apache_vhosts_ssl as such:
```
apache_vhosts_ssl:
  - {
    servername: "local.dev",
    documentroot: "/var/www/html",
    certificate_file: "/home/vagrant/example.crt",
    certificate_key_file: "/home/vagrant/example.key",
    certificate_chain_file: "/path/to/certificate_chain.crt",
    extra_parameters: 'ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"',
  }
```
I'm not sure if this is the correct way to do this, but if so, perhaps adding a note in the documentation would be helpful?
